import { test, expect } from '@playwright/test'

test('JWT inspection, validation and in-memory navigation', async ({ page }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await page.goto('/?tool=jwt')
  await page.getByRole('button', { name: 'Load example' }).click()
  await expect(page.getByText('Within time window', { exact: true })).toBeVisible()
  await expect(page.getByText('Signature unverified', { exact: true })).toBeVisible()
  const input = page.getByRole('textbox', { name: 'Encoded token' })
  const token = await input.inputValue()
  await page.getByRole('button', { name: 'JSON formatter', exact: true }).click()
  await page.getByRole('button', { name: 'JWT decoder', exact: true }).click()
  await expect(input).toHaveValue(token)
  await input.fill('bad.token')
  await expect(page.getByText(/must have three dot-separated/)).toBeVisible()
  await page.reload()
  await expect(input).toHaveValue('')
  expect(errors).toEqual([])
})

test('File diff reads files, compares, clears stale output, and exports patch', async ({ page }) => {
  await page.goto('/?tool=diff')
  const original = page.locator('.editor').filter({ has: page.getByText('Original', { exact: true }) })
  const modified = page.locator('.editor').filter({ has: page.getByText('Modified', { exact: true }) })
  await original.locator('input[type=file]').setInputFiles({ name: 'before.txt', mimeType: 'text/plain', buffer: Buffer.from('hello\nold\n') })
  await modified.locator('input[type=file]').setInputFiles({ name: 'after.txt', mimeType: 'text/plain', buffer: Buffer.from('hello\nnew\n') })
  await page.getByRole('button', { name: 'Compare', exact: true }).click()
  await expect(page.getByText('+1 added', { exact: true })).toBeVisible()
  await expect(page.locator('.diff-line.removed code')).toHaveText('old')
  await expect(page.locator('.diff-line.added code')).toHaveText('new')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Save patch' }).click()
  expect((await download).suggestedFilename()).toBe('comparison.patch')
  await page.getByRole('textbox', { name: 'Modified', exact: true }).fill('other')
  await expect(page.getByRole('button', { name: 'Save patch' })).toBeDisabled()
})

test('Copied JSON formatter supports indent, minify, error locations and local file intake', async ({ page }) => {
  await page.goto('/?tool=json')
  await page.getByRole('textbox', { name: 'Source', exact: true }).fill('{"a":1}')
  await expect(page.locator('.document-preview code')).toContainText('"a": 1')
  await page.getByLabel('Indent size').selectOption('4')
  await expect(page.locator('.document-preview code')).toHaveText('{\n    "a": 1\n}')
  await page.getByRole('button', { name: 'Minified', exact: true }).click()
  await expect(page.locator('.document-preview code')).toHaveText('{"a":1}')
  await page.getByRole('textbox', { name: 'Source', exact: true }).fill('{\n "a":\n}')
  await expect(page.getByText(/line 3, column 1/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Save', exact: true })).toBeDisabled()
})

test('Markdown renders Mermaid and sanitizes scripts and automatic remote images', async ({ page }) => {
  const external = []
  page.on('request', (request) => { if (!request.url().startsWith('http://127.0.0.1:4174') && !request.url().startsWith('data:')) external.push(request.url()) })
  await page.goto('/?tool=markdown')
  await page.getByRole('button', { name: 'Load example' }).click()
  await expect(page.locator('.mermaid[data-state=done] svg')).toBeVisible({ timeout: 20_000 })
  await page.getByRole('textbox', { name: 'Source', exact: true }).fill('# Safe preview\n\n<script>window.unsafe=true</script>\n\n<style>@import "https://example.com/private-css";</style><p style="background-image:url(https://example.com/private-background)">Text</p>\n\n<img src="https://example.com/private-token" onerror="window.unsafe=true">\n\n[Link](javascript:alert(1))')
  await expect(page.locator('.markdown h1')).toContainText('Safe preview')
  await expect(page.locator('.markdown script')).toHaveCount(0)
  await expect(page.locator('.markdown style')).toHaveCount(0)
  await expect(page.locator('.markdown [style]')).toHaveCount(0)
  await expect(page.locator('.markdown img')).not.toHaveAttribute('src')
  expect(await page.evaluate(() => window.unsafe)).toBeUndefined()
  expect(external).toEqual([])
})

test('UTF-8 encoding, timestamp, hashing and UUID generation', async ({ page }) => {
  await page.goto('/?tool=base64')
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('Hello 👋')
  const encoded = await page.getByRole('textbox', { name: 'Result', exact: true }).inputValue()
  await page.getByRole('button', { name: 'Use result as input' }).click()
  await expect(page.getByRole('textbox', { name: 'Result', exact: true })).toHaveValue('Hello 👋')
  expect(encoded).toBe('SGVsbG8g8J+Riw==')
  await page.getByRole('button', { name: 'Timestamp converter', exact: true }).click()
  await page.getByLabel('Timestamp or ISO date').fill('0')
  await expect(page.getByText('1970-01-01T00:00:00.000Z', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Hash generator', exact: true }).click()
  await page.getByRole('textbox', { name: 'Text to hash' }).fill('abc')
  await expect(page.locator('.hash-result pre')).toHaveText('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
  await page.getByRole('button', { name: 'UUID generator', exact: true }).click()
  await page.getByRole('spinbutton').fill('3')
  await page.getByRole('button', { name: 'Generate UUIDs', exact: true }).click()
  const uuids = (await page.getByRole('textbox', { name: 'UUIDs · version 4' }).inputValue()).split('\n')
  expect(uuids).toHaveLength(3)
  expect(new Set(uuids).size).toBe(3)
})

test('Mobile navigation, search, theme and responsive layouts', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'A little less friction.' })).toBeVisible()
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
  await page.getByRole('textbox', { name: 'Find a tool' }).fill('jwt')
  await page.getByRole('textbox', { name: 'Find a tool' }).press('Enter')
  await expect(page.getByRole('heading', { name: 'JWT decoder' })).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Open navigation', exact: true }).click()
  await page.getByRole('button', { name: /Switch to .* mode/ }).click()
  const theme = await page.locator('html').getAttribute('data-theme')
  await page.reload()
  await expect(page.locator('html')).toHaveAttribute('data-theme', theme)
})

test('Remaining tools, clipboard, downloads, browser history and visual review', async ({ page, context }) => {
  const errors = []
  page.on('pageerror', (error) => errors.push(error.message))
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await page.evaluate(() => { document.documentElement.dataset.theme = 'light' })
  await expect(page.getByRole('button', { name: 'Open navigation', exact: true })).not.toBeVisible()
  await page.screenshot({ path: '/tmp/utils-overview.png', fullPage: true })
  for (const [id, source] of [['html', '<main><h1>Hello</h1></main>'], ['xml', '<root><value>hello</value></root>']]) {
    await page.goto(`/?tool=${id}`)
    await page.getByRole('textbox', { name: 'Source', exact: true }).fill(source)
    await expect(page.locator('.document-preview code')).toContainText('hello', { ignoreCase: true })
    await page.getByRole('button', { name: 'Full width', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Source', exact: true })).not.toBeVisible()
    await page.getByRole('button', { name: 'Split view', exact: true }).click()
    await expect(page.getByRole('textbox', { name: 'Source', exact: true })).toBeVisible()
  }
  await page.goto('/?tool=url')
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('a+b & café')
  await expect(page.getByRole('textbox', { name: 'Result' })).toHaveValue('a%2Bb%20%26%20caf%C3%A9')
  await page.getByRole('button', { name: 'Copy', exact: true }).click()
  await expect.poll(() => page.evaluate(() => navigator.clipboard.readText())).toBe('a%2Bb%20%26%20caf%C3%A9')
  await page.getByRole('button', { name: 'Decode', exact: true }).click()
  await page.getByRole('textbox', { name: 'Input', exact: true }).fill('%zz')
  await expect(page.getByText(/Invalid URL encoding/)).toBeVisible()
  await page.getByRole('button', { name: 'Hash generator', exact: true }).click()
  await page.locator('.tool-content:not([hidden]) input[type=file]').first().setInputFiles({ name: 'abc.bin', mimeType: 'application/octet-stream', buffer: Buffer.from('abc') })
  await expect(page.locator('.hash-result pre')).toHaveText('ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad')
  await page.goBack()
  await expect(page.getByRole('heading', { name: 'URL encoder', exact: true })).toBeVisible()
  await page.goto('/?tool=jwt')
  await page.getByRole('button', { name: 'Load example' }).click()
  await page.screenshot({ path: '/tmp/utils-jwt.png', fullPage: true })
  await page.goto('/?tool=diff')
  await page.getByRole('button', { name: 'Load example' }).click()
  await page.getByRole('button', { name: 'Compare', exact: true }).click()
  await expect(page.getByText('+3 added', { exact: true })).toBeVisible()
  await page.screenshot({ path: '/tmp/utils-diff.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.screenshot({ path: '/tmp/utils-mobile-diff.png', fullPage: true, animations: 'disabled' })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  expect(errors).toEqual([])
})
